dist: trusty
sudo: required
group: beta
language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
install: npm install
script:
  - npm run build
before_deploy:
  - cd www
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: $AWS_S3_BUCKET
  skip_cleanup: true
  acl: public_read
  upload-dir: $AWS_S3_BUCKET_DIR
  on:
    branch: develop