dist: trusty
sudo: required
group: beta
language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
install: npm install
script:
  - npm run lint
  - npm run build
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: $AWS_S3_BUCKET
    local_dir: out
    skip_cleanup: true
    acl: public_read
    on:
      branch: develop
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: $AWS_S3_PROD_BUCKET
    local_dir: out
    skip_cleanup: true
    acl: public_read
    on:
      branch: feature/estimate_call_gas
notifications:
  slack:
    secure: qkdXsAm7sEaBl7nr/9JROTT8e0ZJnUbmIfzmsyHqmwtsavA7kQMX1zh2yE3qVzvq5VaBZI8lUT1woAu+9OGwUBLB4o29PRLiGlKcziF26dpRZyFhWh9lU453e3+ezlCfC5t+jn0ySf6tXaRHsJa8JfvKoAyG0ex99i+ogybizOqHaY6uzNfxsdTq9jIwuN+16V8YkQB9gDsPVqvrBRMnfsnlw/EnCEnuUST2YEK+FFiRer6+5zV/pDUvdAREvFqZ4pH7DyK3uK4kS7KbHQWF6YqTqu7TBg2vEMzwpkIOWVnhLQXrFJUxXfeFAX5CWyHJs0CLbHHmbvJ02+fY8pWwT40GEyuGHTGRAv5PHSj2xxkomUbuVmt11essJdoO7GN5HhH9fFxUNPyDzNYW8fz3hFgf6Yioh+aSkGLh04e5y4VKwIc011u6za6lFmJ06ZrkHIpIqouN5D3LLvSfBZJstnF/MvRqL3je6jvSN09J9LRdyoW6us8t/dBUL/1iOQ4FVHnFg45EcQ9rY63EcHch23j63fd1Rg4L4zhnVImtdAlfZF7TAiBWPhTCWRVBUMLy1QoBI57ZFQXUDFgOrpQCSifLMVIMjf34FhIoIkIs4Y57hukiDQAEDK/mhcHqWlM9NWPvtaC2e5P2Dg31213fbaCQ9MrKoL1odYSxaHS2Scc=
