version: '3.4'
services:
    eth-alarm-clock-dapp.public.dappnode.eth:
        image: 'eth-alarm-clock-dapp.public.dappnode.eth:1.1.6'
        build: ./build
        volumes:
            - 'ipfsdnpdappnodeeth_export:/export'
            - '/home/ipfs_data:/data/ipfs'
volumes:
    ipfsdnpdappnodeeth_export: {}
